 spring:
  datasource:
    url: jdbc:h2:mem:mydb
    driverClassName: org.h2.Driver
    username: sa
    password: ""
  h2:
    console:
      enabled: true
  config:
    import:
      optional:file:.env[.properties]
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: Iv23liR7WVaV3RdHasqZ
            client-secret: e033314f81749bfb0ad362b73366c2b04abe1b0d
            provider: github
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            provider: google
 server:
   error:
     whitelabel:
       enabled: false